### ISSUE TITLE
No issue. But would love to help.

### ISSUE THREAD

**Issue by mmoonport** [vitramir/apollo-model-mongodb#1]
I would love to help you move this project along as i was about to start building the same thing. Great code btw.

**Comment by vitramir** [comment]
Thank you.
Let's build chat room at any app, to speed up communication. I prefer spectrum, but may be you know something better?

**Comment by mmoonport** [comment]
We could use discord. I have created a room on there and its free.
https://discord.gg/v3Qrajy
